### ISSUE TITLE
Build fails with electron-builder

### ISSUE THREAD

**Issue by magne4000** [colinskow/rx-ipc-electron#4]
When `rx-ipc-electron` is installed (not even required), building with `electron-builder` triggers an error during codesign step:

```
Error: Command failed: codesign --sign XXXXXXX --force /Users/magne/workspace/browserX/release/mac/Station Canary.app/Contents/Resources/app.asar.unpacked/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework
/Users/magne/workspace/browserX/release/mac/Station Canary.app/Contents/Resources/app.asar.unpacked/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework: bundle format unrecognized, invalid, or unsuitable
```
Removing the package from `package.json` makes the issue disappear.

Do you have any idea why ?

**Comment by alexstrat** [comment]
It seems that having electron as peerDependency is the issue here.
https://github.com/getstation/rx-ipc-electron/pull/1/commits/ffd02bed390dc498827990b36201873a95349409
